# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_document_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinker',
            new_name='UserModule',
        ),
    ]
