# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20160106_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
