# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20160106_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fx',
            field=models.BooleanField(default=False),
        ),
    ]
